config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :post_attachments
  resources :regions
  resources :posts
  resources :entertainment_parent_companies

  resources :entertainments do
   collection do
    post 'dumy_update'
    get 'initial_page' 
    get 'report'
    get 'function_rep'
    get 'report_by_function'
    get 'report_by_country'
    get 'report_by_rep'
    get 'report_by_stateorprovince'
    get 'dap_entertainments'

   end
   member do
    get 'edit_dap'
    patch 'update_dap'
   end 
  end
  resources :paintings do
    member do
      patch 'update_funny_image'
    end
    collection do
      post 'create_funny_image'
    end     
  end
  match "/entertainments/report/:country/:rep/:function/:state" => "entertainments#report", via: [:get]
  resources :products
  resources :home
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}

  devise_scope :user do
  
  get '/users/subregion_options' => 'registrations#subregion_options'
  authenticated :user do
    root :to => 'devise/registrations#edit', as: :authenticated_root
  end
  
  unauthenticated :user do
    root :to => 'devise/sessions#new', as: :unauthenticated_root
  end
end

end

app/models/entertainment.rb
class Entertainment < ActiveRecord::Base
	belongs_to :user
	belongs_to :entertainment_parent_company, :foreign_key => :ee_user_id
	validates_presence_of :country, :name, :function
	validate :at_least_one_field

	def at_least_one_field
	  if [self.url, self.phone_number, self.street_address_1, self.email ].reject(&:blank?).size == 0
	    errors[:base] << ("Please choose at least one field (URl or Phone Number or Street Address 1 or email)")
	  end
	end     
end

app/controllers/entertainments_controller.rb
class EntertainmentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :custome_auth,  only: [ :edit, :update, :index, :dap_entertainmentsm, :edit_dap, :update_dap ]
  before_filter :current_user_to_model

	def index
    respond_to do |format|
    format.html
    format.json { render json: ::EntertainmentsDatatable.new(view_context) }
    end
  end

  def show
  end

  def new
   @entertainment = Entertainment.new
    @entertainment.representative_name = current_user.try(:first_name)+" #{current_user.try(:middle_name)} "+current_user.try(:last_name)
    @entertainment.representative_id = current_user.try(:user_main_id)
    @entertainment.division = current_user.try(:division).try(:name)
    @entertainment.region = current_user.try(:region).try(:name)
    password_length = 12
    @entertainment.password = Devise.friendly_token.first(password_length)
    @entertainment.ee_user_id = Entertainment.order("id desc").first.id
    @function = ''    
  end

  def edit
    @entertainment = Entertainment.find(params[:id])
    if(@entertainment.entertainment_parent_company.nil?)
      password_length = 12
      @password = Devise.friendly_token.first(password_length)
      @entertainment.ee_user_id = EntertainmentParentCompany.create(password: @password).id
      @entertainment.save(:validate => false)
    end  
    redirect_to edit_entertainment_parent_company_path
    
    


    @entertainment_parent_company =  EntertainmentParentCompany.find(@entertainment.ee_user_id)

    #  @entertainment.parent_company_postal_code = @entertainment_parent_company.parent_company_postal_code
    #   @entertainment.parent_company_street_address_2 = @entertainment_parent_company.parent_company_street_address_2
    #   @entertainment.parent_company_street_address_1 = @entertainment_parent_company.parent_company_street_address_1
    #   @entertainment.parent_company_city  = @entertainment_parent_company.parent_company_city 
    #   @entertainment.parent_company_contact_person_salutation = @entertainment_parent_company.parent_company_contact_person_salutation
    #   @entertainment.parent_company_state_or_province = @entertainment_parent_company.parent_company_state_or_province
    #   @entertainment.parent_company_contact_person_email_address = @entertainment_parent_company.parent_company_contact_person_email_address
    #   @entertainment.parent_company_contact_person_last_name = @entertainment_parent_company.parent_company_contact_person_last_name
    #   @entertainment.parent_company_country = @entertainment_parent_company.parent_company_country
    #   @entertainment.parent_company_contact_person_phone_number = @entertainment_parent_company.parent_company_contact_person_phone_number
    #   @entertainment.parent_company_contact_person_first_name = @entertainment_parent_company.parent_company_contact_person_first_name
    #   @entertainment.parent_comapny_name  = @entertainment_parent_company.parent_comapny_name 
    #   @entertainment.webpage_director_phone_number = @entertainment_parent_company.webpage_director_phone_number
    #   @entertainment.webpage_director_email_address = @entertainment_parent_company.webpage_director_email_address
    #   @entertainment.webpage_director_salutation = @entertainment_parent_company.webpage_director_salutation
    #   @entertainment.webpage_director_last_name = @entertainment_parent_company.webpage_director_last_name
    #   @entertainment.webpage_director_contact_person_first_name = @entertainment_parent_company.webpage_director_contact_person_first_name
    #   @entertainment.webpage_director_company = @entertainment_parent_company.webpage_director_company
    #   @entertainment.webpage_director_first_name = @entertainment_parent_company.webpage_director_first_name
    #   @entertainment.webpage_director_skype_id = @entertainment_parent_company.webpage_director_skype_id
    #   @entertainment.password = @entertainment_parent_company.password
    #   @entertainment.parent_company_contact_person_skype_id = @entertainment_parent_company.parent_company_contact_person_skype_id
    # @function = @entertainment.function
  end

  def create

    @entertainment = current_user.entertainments.build(entertainment_params)

    respond_to do |format|
      if @entertainment.save
        format.html { redirect_to new_entertainment_path, notice: 'Entertainment was successfully established.' }
        format.json { render :show, status: :created, location: @entertainment }
      else
        format.html { render :new }
        format.json { render json: @entertainment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @entertainment = Entertainment.find(params[:id])
    @entertainment_parent_company = EntertainmentParentCompany.find(@entertainment.ee_user_id)
    
    respond_to do |format|
      if @entertainment.update(entertainment_params) and @entertainment_parent_company.update(entertainment_parent_company_params) 
        format.html { redirect_to entertainments_path, notice: 'Entertainment was successfully updated.' }
        format.json { render :show, status: :ok, location: @entertainment }
      else
        format.html { render :edit }
        format.json { render json: @entertainment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @entertainment = current_user.entertainments.find(params[:id])
    @entertainment.destroy
    respond_to do |format|
      format.html { redirect_to entertainments_url, notice: 'Entertainment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def report
     puts "ss"*22
     puts params.inspect
     puts Carmen::Country.coded(params[:country]).inspect 
     puts "ss"*22
    if current_user.role.present?
      if current_user.role.name == "Senior Director"
        @entertainments = Entertainment.where("country='#{params[:country]}' or representative_id='#{params[:rep]}' or function='#{params[:function]}' or state_or_province='#{params[:state]}'").limit(100).offset(0).order("function desc").order("category desc").order("country asc").order("state_or_province asc").order("name asc")
      elsif current_user.role.name == "Divisional Director"
        @entertainments = Entertainment.where(division: current_user.division.name).where("country='#{params[:country]}' or representative_id='#{params[:rep]}' or function='#{params[:function]}' or state_or_province='#{params[:state]}'").limit(100).offset(0).order("function desc").order("category desc").order("country asc").order("state_or_province asc").order("name asc")
      else
        @entertainments = Entertainment.where(region: current_user.region.name).where("country='#{params[:country]}' or representative_id='#{params[:rep]}' or function='#{params[:function]}' or state_or_province='#{params[:state]}'").limit(100).offset(0).order("function desc").order("category desc").order("country asc").order("state_or_province asc").order("name asc")  
      end
    else
      @entertainments = Entertainment.where(region: current_user.region.name).where("country='#{params[:country]}' or representative_id='#{params[:rep]}' or function='#{params[:function]}' or state_or_province='#{params[:state]}'").limit(100).offset(0).order("function desc").order("category desc").order("country asc").order("state_or_province asc").order("name asc")
    end
  end

  def report_by_function
    @count = {}
    if current_user.role.present?
      if current_user.role.name == "Senior Director"
        @entertainments = Entertainment.all.limit(100).offset(0).order("function desc").order("category desc").order("country asc").order("state_or_province asc").order("name asc")
        @by = Entertainment.uniq.pluck(:function)
        @by.each do |function|
          @count[function] = Entertainment.where(function: function).count
        end
      elsif current_user.role.name == "Divisional Director"
        @entertainments = Entertainment.where(division: current_user.division.name).limit(100).offset(0).order("function desc").order("category desc").order("country asc").order("state_or_province asc").order("name asc")
        @by = Entertainment.where(division: current_user.division.name).order("function asc").uniq.pluck(:function)
        @by.each do |function|
          @count[function] = Entertainment.where(function: function, division: current_user.division.name).count 
        end
      else
        @entertainments = Entertainment.where(region: current_user.region.name).limit(100).offset(0).order("function desc").order("category desc").order("country asc").order("state_or_province asc").order("name asc")
        @by = Entertainment.where(region: current_user.region.name).order("function asc").uniq.pluck(:function)  
        @by.each do |function|
          @count[function] = Entertainment.where(function: function, region: current_user.region.name).count 
        end
      end
    else
      @entertainments = Entertainment.where(region: current_user.region.name).limit(100).offset(3).order("function desc").order("category desc").order("country asc").order("state_or_province asc").order("name asc")
      @by = Entertainment.where(region: current_user.region.name).order("function asc").uniq.pluck(:function)
      @by.each do |function|
          @count[function] = Entertainment.where(function: function, region: current_user.region.name).count 
      end
    end
  end

  def function_rep
    
    if current_user.role.name == "Senior Director"
      @entertainments = Entertainment.where("country='#{params[:country]}' or representative_id='#{params[:rep]}' or function='#{params[:function]}' or state_or_province='#{params[:state]}'").limit(100).offset(params[:offset]).order("function desc").order("category desc").order("country asc").order("state_or_province asc").order("name asc")
    elsif current_user.role.name == "Divisional Director"

app/helpers/entertainments_helper.rb
module EntertainmentsHelper
end

app/views/entertainments/_form.html.erb
<%= form_for @entertainment, :html => { :class => "form-horizontal entertainment" } do |f| %>

    <% if @entertainment.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@entertainment.errors.count, "error") %> prohibited this entertainment from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @entertainment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="DAP1-info">   
  <h3 class="region-breaker"> DAP 1 INFO </h3>
  
  <div class="control-group col-md-6">
    <div class="controls">
      <%= f.text_field :representative_name, :class => 'form-control', :readonly => true %>
    </div>
    <%= f.label :representative_name,"Representative Name", :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:representative_name]) %>
  </div>
  <div class="control-group col-md-6">
    <div class="controls">
      <%= f.text_field :representative_id, :class => 'form-control', :readonly => true %>
    </div>
    <%= f.label :representative_id,"Representative Id", :class => 'control-label user_feild disable' %>

    <%= error_span(@entertainment[:representative_id]) %>
  </div>
  <div class="control-group col-md-6">
    <div class="controls">
      <%= f.country_select :city, priority: %w(US CA), prompt: 'Please select a city',class: "form-control" %>
    </div>
    <%= f.label :city, :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:city]) %>
  </div>
  <div class="control-group col-md-6">
    <div class="controls">
      <%= f.country_select :country, priority: %w(US CA), prompt: 'Please select a country',class: "form-control" %>
    </div>
    <%= f.label :country, :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:country]) %>
  </div>
  
   <div class="control-group col-md-6">
    <div class="controls">
      <%= f.text_field :url, :class => 'form-control' %>
    </div>
    <%= f.label :url, :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:url]) %>
  </div>
   <div class="control-group col-md-6">
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= f.label :name, "EE Name", :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:name]) %>
  </div>
  <div class="control-group col-md-6">
    <div class="controls">
      <%= f.email_field :email, :class => 'form-control' %>
    </div>
    <%= f.label :email,"Email", :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:email]) %>
  </div>
 <div class="control-group col-md-6">
    <div class="controls">
      <%= f.text_field :phone_number, :class => 'form-control' %>
    </div>
    <%= f.label :phone_number,"Phone Number", :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:phone_number]) %>
  </div>
  <div class="control-group col-md-6">
    <div class="controls">
      <%= f.text_field :street_address_1, :class => 'form-control' %>
    </div>
    <%= f.label :street_address_1,"Street Address 1", :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:street_address_1]) %>
  </div>
  <div class="control-group col-md-6">
    <div class="controls">
      <%= f.text_field :street_address_2, :class => 'form-control' %>
    </div>
    <%= f.label :street_address_2,"Street Address 2", :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:street_address_2]) %>
  </div> 
  <div class="control-group col-md-6">
      
      <%= f.text_field :function ,:value => "N/A", hidden: "hidden" %>
  </div>
 <%= hidden_field_tag "division", current_user.try(:division).try(:name) %>
 <%= hidden_field_tag "region", current_user.try(:division).try(:name) %>
  
  
   

  <%= f.submit nil, :class => 'btn btn-primary col-md-12' %>
  
<% end %>

app/views/entertainments/_report.html.erb
<%- model_class = Entertainment -%>
<div class="table_area">
<table id="flip-scroll" class="table table-bordered table-striped tablesorter report">
  <thead>
    <tr>
      <th class="text-center">-</th>
      <th class="text-center">-</th>
      <th colspan="7" >Sort All Columns</th>
    </tr>
    <tr>
      <th class="text-center">-</th>
      <th class="text-center">-</th>
      <th colspan="2" >First Group</th>
      <th colspan="5" >Second Group</th>
    </tr>
    <tr>
      <th>Action</th>
      <th><%= model_class.human_attribute_name(:representative_id) %></th>
      <th class="numeric"><%= model_class.human_attribute_name(:country) %></th>
      <th class="numeric"><%= model_class.human_attribute_name(:state_or_province) %></th>
      <th><%= model_class.human_attribute_name(:function) %></th>
      <th class="numeric"><%= model_class.human_attribute_name(:category) %></th>
      <th class="numeric"><%= model_class.human_attribute_name(:sub_category) %></th>
      <th class="numeric"><%= model_class.human_attribute_name(:name) %></th>
      <th class="numeric"><%= model_class.human_attribute_name(:url) %></th>
      <th class="numeric"><%= model_class.human_attribute_name(:created_at) %></th>
      <th class="numeric">Last edited</th>
    </tr>
  </thead>
  <tbody>
    <% @entertainments.each do |entertainment| %> 
      <tr>
        <td data-title="Action"><%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_entertainment_path(entertainment), :class => 'btn btn-default btn-xs' %></td>
        <td data-title="Representative"><%= entertainment.representative_id %></td>
        <td data-title="Country" class="numeric"><%= Carmen::Country.coded(entertainment.country).name %></td>
        <td data-title="State or province" class="numeric"><%= entertainment.state_or_province %></td>
        <td data-title="Function"><%= entertainment.function %></td>
        <td data-title="Category" class="numeric"><%= entertainment.category %></td>
        <td data-title="Sub category %" class="numeric"><%= entertainment.sub_category %></td>
        <td data-title="Name" class="numeric"><%= entertainment.name %></td>
        <td data-title="Url" class="numeric"><%= link_to(entertainment.url,entertainment.url) %></td>
        <td data-title="Created at" class="numeric"><%= entertainment.created_at %></td> 
        <td data-title="Last edited" class="numeric"><%= entertainment.updated_at %></td> 
                
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= link_to 'See more', 'javascript:void(0)', :id => "new_product_link", class: "btn col-md-5 btn-border backgrnd-enter-btns see-more" %>
<script type="text/javascript">
  $("table").tablesorter({ theme: 'blue',
  widgets: ["zebra", "filter"],
    widgetOptions : {
      // filter_anyMatch replaced! Instead use the filter_external option
      // Set to use a jQuery selector (or jQuery object) pointing to the
      // external filter (column specific or any match)
      filter_external : '.search',
      // add a default type search to the first name column
      filter_defaultFilter: { 1 : '~{query}' },
      // include column filters
      filter_columnFilters: true,
      filter_placeholder: { search : 'Search...' },
      filter_saveFilters : false,
      filter_reset: '.reset'
    } });
   var offset = 100;
  $(document).ready(function() {
   
    $('#new_product_link').click(function () {
    result = window.location.pathname.split('/');

      $.ajax({
        url: "/entertainments/function_rep",
        type: "get",
        dataType: 'JSON',
        data: {
            'offset' : offset,
            'country' : result[3],
            'rep' : result[4],
            'function' : result[5],
            'state' : result[6]
          },
        success:function(data){
          console.log(data[0]['id']);
          offset = offset+100;
            for (index = 0; index < data.length; ++index) {
              $(".report").append('<tr><td><a class="btn btn-default btn-xs" href="/entertainments/'+data[index]['id']+'/edit">Edit</a></td><td>'+data[index]['representative_id']+'</td><td>'+data[index]['country']+'</td><td>'+data[index]['state_or_province']+'</td><td>'+data[index]['function']+'</td><td>'+data[index]['category']+'</td><td>'+data[index]['sub_category']+'</td><td>'+data[index]['name']+'</td></td><td><a href="'+data[index]['url']+'">'+data[index]['url']+'</a></td><td>'+data[index]['created_at']+'<td>'+data[index]['updated_at']+'</tr>');
            }    
          }  
        });
      }); 
    }); 
</script>

app/views/entertainments/dap_entertainments.html.erb
<% javascript_include_tag "entertainments_of_DAP.js" %>
<%- model_class = Entertainment -%>
<div class="page-header">
  <h1><%=t '.title', :default => "DAP "+model_class.model_name.human.pluralize.titleize %></h1>
</div>


<table id="entertainments" class="table table-striped edit" data-source="<%= dap_entertainments_entertainments_url(format: "json") %>">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= "EE "+model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th>DAP Name</th>
      <th>Action</th>
    </tr>
  </thead>
</table>

app/views/entertainments/edit.html.erb
<%- model_class = Entertainment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/entertainments/edit_dap.html.erb
<%- model_class = Entertainment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= form_for @entertainment, url: update_dap_entertainment_path,  :html => { :class => "form-horizontal entertainment" } do |f| %>

    <% if @entertainment.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@entertainment.errors.count, "error") %> prohibited this entertainment from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @entertainment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="DAP1-info">   
  <h3 class="region-breaker"> DAP 1 INFO </h3>
  
  <div class="control-group col-md-6">
    <div class="controls">
      <%= f.text_field :representative_name, :class => 'form-control', :disabled => 'disabled' %>
    </div>
    <%= f.label :representative_name,"Representative Name", :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:representative_name]) %>
  </div>
  <div class="control-group col-md-6">
    <div class="controls">
      <%= f.text_field :representative_id, :class => 'form-control', :disabled => 'disabled' %>
    </div>
    <%= f.label :representative_id,"Representative Id", :class => 'control-label user_feild disable' %>

    <%= error_span(@entertainment[:representative_id]) %>
  </div>
  <div class="control-group col-md-6">
    <div class="controls">
      <%= f.country_select :city, priority: %w(US CA), prompt: 'Please select a city',class: "form-control" %>
    </div>
    <%= f.label :city, :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:city]) %>
  </div>
  <div class="control-group col-md-6">
    <div class="controls">
      <%= f.country_select :country, priority: %w(US CA), prompt: 'Please select a country',class: "form-control" %>
    </div>
    <%= f.label :country, :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:country]) %>
  </div>
  
   <div class="control-group col-md-6">
    <div class="controls">
      <%= f.text_field :url, :class => 'form-control' %>
    </div>
    <%= f.label :url, :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:url]) %>
  </div>
   <div class="control-group col-md-6">
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= f.label :name, "EE Name", :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:name]) %>
  </div>
  <div class="control-group col-md-6">
    <div class="controls">
      <%= f.email_field :email, :class => 'form-control' %>
    </div>
    <%= f.label :email,"Email", :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:email]) %>
  </div>
 <div class="control-group col-md-6">
    <div class="controls">
      <%= f.text_field :phone_number, :class => 'form-control' %>
    </div>
    <%= f.label :phone_number,"Phone Number", :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:phone_number]) %>
  </div>
  <div class="control-group col-md-6">
    <div class="controls">
      <%= f.text_field :street_address_1, :class => 'form-control' %>
    </div>
    <%= f.label :street_address_1,"Street Address 1", :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:street_address_1]) %>
  </div>
  <div class="control-group col-md-6">
    <div class="controls">
      <%= f.text_field :street_address_2, :class => 'form-control' %>
    </div>
    <%= f.label :street_address_2,"Street Address 2", :class => 'control-label user_feild' %>

    <%= error_span(@entertainment[:street_address_2]) %>
  </div> 
  <div class="control-group col-md-6">
      
      <%= f.text_field :function ,:value => "N/A", hidden: "hidden" %>
      
  </div>
 <%= hidden_field_tag "division", current_user.try(:division).try(:name) %>
 <%= hidden_field_tag "region", current_user.try(:division).try(:name) %>
  
  
   

  <%= f.submit nil, :class => 'btn btn-primary col-md-12' %>
  
<% end %>

app/views/entertainments/index.html.erb
<%- model_class = Entertainment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<% if current_user.role.name != "Data Acquisition Personnel" %>
<div class="col-md-12 btn_area">
  <%= link_to "Total EE's", report_entertainments_path, :class => 'btn col-md-5 btn-border backgrnd-enter-btns'%>
  <%= link_to "EE's By COUNTRY", report_by_country_entertainments_path, :class => 'btn col-md-5 btn-border backgrnd-enter-btns'%>
</div>
<div class="col-md-12 btn_area">
  <%= link_to "EE's By REP", report_by_rep_entertainments_path, :class => 'btn col-md-5 btn-border backgrnd-enter-btns'%>
  <%= link_to "EE's By FUNCTION", report_by_function_entertainments_path, :class => 'btn col-md-5 btn-border backgrnd-enter-btns'%>
</div>
<div class="col-md-12 btn_area">
  <%= link_to "EE's By State", report_by_stateorprovince_entertainments_path, :class => 'btn col-md-5 btn-border backgrnd-enter-btns'%>
</div>
<%end%>

<table id="entertainments" class="table table-striped edit" data-source="<%= entertainments_url(format: "json") %>">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= "EE "+model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:state_or_province) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <% if current_user.role.name != "Data Acquisition Personnel" %>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
</table>

app/views/entertainments/initial_page.html.erb
<% if current_user.try(:role).try(:name) == "Data Acquisition Personnel"%>
	<%= link_to "ADD", new_entertainment_path, { :class=>"btn btn_side image-upload btn_add "}%>
<% else %>
	<%= link_to "ADD", new_entertainment_parent_company_path, { :class=>"btn btn_side image-upload btn_add "}%>
<%end%>	
<%= link_to "EDIT", entertainments_path, { :class=>"btn btn_side image-upload btn_add"}%>

app/views/entertainments/new.html.erb
<% javascript_include_tag "entertainments.js" %>
<%- model_class = Entertainment -%>
<div>
</div>
<div class="page-header">
  <h3><b><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></b>
  </h3>
</div>
  
<%= render :partial => 'form' %>
<br/><br/>

app/views/entertainments/report.html.erb
<div class="page-header">
  <h1>Total Report</h1>
</div>
<%= render :partial => 'report' %>

app/views/entertainments/report_by_country.html.erb
<div class="page-header">
  <h1>Report By Country</h1>
</div>
<%- model_class = Entertainment -%>
<table id="flip-scroll" class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th class="numeric">Count</th>
    </tr>
  </thead>
  <tbody>
    <% @by.each do |entertainment| %> 
      <tr>
        <td data-title="Country %" class="numeric"><%= link_to Carmen::Country.coded(entertainment).name,'/entertainments/report/'+entertainment+'/1/1/1/', :class => 'undecorate'  %></td>
        <td data-title="Url" class="numeric"><%= @count[entertainment] %></td>
      </tr>
    <% end %>
  </tbody>
</table>