config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :post_attachments
  resources :regions
  resources :posts
  resources :entertainment_parent_companies

  resources :entertainments do
   collection do
    post 'dumy_update'
    get 'initial_page' 
    get 'report'
    get 'function_rep'
    get 'report_by_function'
    get 'report_by_country'
    get 'report_by_rep'
    get 'report_by_stateorprovince'
    get 'dap_entertainments'

   end
   member do
    get 'edit_dap'
    patch 'update_dap'
   end 
  end
  resources :paintings do
    member do
      patch 'update_funny_image'
    end
    collection do
      post 'create_funny_image'
    end     
  end
  match "/entertainments/report/:country/:rep/:function/:state" => "entertainments#report", via: [:get]
  resources :products
  resources :home
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}

  devise_scope :user do
  
  get '/users/subregion_options' => 'registrations#subregion_options'
  authenticated :user do
    root :to => 'devise/registrations#edit', as: :authenticated_root
  end
  
  unauthenticated :user do
    root :to => 'devise/sessions#new', as: :unauthenticated_root
  end
end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/assigned_region.rb
class AssignedRegion < ActiveRecord::Base
belongs_to :user
belongs_to :region
end

app/models/division.rb
class Division < ActiveRecord::Base
has_many :users
end

app/models/entertainment.rb
class Entertainment < ActiveRecord::Base
	belongs_to :user
	belongs_to :entertainment_parent_company, :foreign_key => :ee_user_id
	validates_presence_of :country, :name, :function
	validate :at_least_one_field

	def at_least_one_field
	  if [self.url, self.phone_number, self.street_address_1, self.email ].reject(&:blank?).size == 0
	    errors[:base] << ("Please choose at least one field (URl or Phone Number or Street Address 1 or email)")
	  end
	end     
end

app/models/funny_image.rb
class FunnyImage < ActiveRecord::Base
belongs_to :user		
mount_uploader :image, ImageUploader
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  belongs_to :user		
  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/region.rb
class Region < ActiveRecord::Base
has_many :users
has_many :territories
end

app/models/role.rb
class Role < ActiveRecord::Base
has_one :user	
end

app/models/territory.rb
class Territory < ActiveRecord::Base
belongs_to :region
belongs_to :division
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :painting
  has_one :funny_image
  belongs_to :region, foreign_key: "region_id"
  belongs_to :division
  has_many :entertainments
  belongs_to :role
  validates_uniqueness_of :user_main_id
  # validates_presence_of :role_id, :division_id, :region_id
  validates_presence_of :country_of_residence
  #validates_numericality_of :age, :only_integer =>true, 
  #                        :greater_than_or_equal_to =>0, 
  #                        :message => "invalid"
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 before_filter :authenticate_user!	
	def index
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper

	def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
  
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/entertainments_helper.rb
module EntertainmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/post_attachments/_form.html.erb
<%= form_for(@post_attachment) do |f| %>
  <% if @post_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_attachment.errors.count, "error") %> prohibited this post_attachment from being saved:</h2>

      <ul>
      <% @post_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_attachments/edit.html.erb
<h1>Editing post_attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_attachment %> |
<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/index.html.erb
<h1>Listing post_attachments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_attachments.each do |post_attachment| %>
      <tr>
        <td><%= post_attachment.post_id %></td>
        <td><%= post_attachment.avatar %></td>
        <td><%= link_to 'Show', post_attachment %></td>
        <td><%= link_to 'Edit', edit_post_attachment_path(post_attachment) %></td>
        <td><%= link_to 'Destroy', post_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post attachment', new_post_attachment_path %>

app/views/post_attachments/new.html.erb
<h1>New post_attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post_attachment.post_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @post_attachment.avatar %>
</p>

<%= link_to 'Edit', edit_post_attachment_path(@post_attachment) %> |
<%= link_to 'Back', post_attachments_path %>