config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :post_attachments
  resources :regions
  resources :posts
  resources :entertainment_parent_companies

  resources :entertainments do
   collection do
    post 'dumy_update'
    get 'initial_page' 
    get 'report'
    get 'function_rep'
    get 'report_by_function'
    get 'report_by_country'
    get 'report_by_rep'
    get 'report_by_stateorprovince'
    get 'dap_entertainments'

   end
   member do
    get 'edit_dap'
    patch 'update_dap'
   end 
  end
  resources :paintings do
    member do
      patch 'update_funny_image'
    end
    collection do
      post 'create_funny_image'
    end     
  end
  match "/entertainments/report/:country/:rep/:function/:state" => "entertainments#report", via: [:get]
  resources :products
  resources :home
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}

  devise_scope :user do
  
  get '/users/subregion_options' => 'registrations#subregion_options'
  authenticated :user do
    root :to => 'devise/registrations#edit', as: :authenticated_root
  end
  
  unauthenticated :user do
    root :to => 'devise/sessions#new', as: :unauthenticated_root
  end
end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/assigned_region.rb
class AssignedRegion < ActiveRecord::Base
belongs_to :user
belongs_to :region
end

app/models/division.rb
class Division < ActiveRecord::Base
has_many :users
end

app/models/entertainment.rb
class Entertainment < ActiveRecord::Base
	belongs_to :user
	belongs_to :entertainment_parent_company, :foreign_key => :ee_user_id
	validates_presence_of :country, :name, :function
	validate :at_least_one_field

	def at_least_one_field
	  if [self.url, self.phone_number, self.street_address_1, self.email ].reject(&:blank?).size == 0
	    errors[:base] << ("Please choose at least one field (URl or Phone Number or Street Address 1 or email)")
	  end
	end     
end

app/models/funny_image.rb
class FunnyImage < ActiveRecord::Base
belongs_to :user		
mount_uploader :image, ImageUploader
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  belongs_to :user		
  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/region.rb
class Region < ActiveRecord::Base
has_many :users
has_many :territories
end

app/models/role.rb
class Role < ActiveRecord::Base
has_one :user	
end

app/models/territory.rb
class Territory < ActiveRecord::Base
belongs_to :region
belongs_to :division
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :painting
  has_one :funny_image
  belongs_to :region, foreign_key: "region_id"
  belongs_to :division
  has_many :entertainments
  belongs_to :role
  validates_uniqueness_of :user_main_id
  # validates_presence_of :role_id, :division_id, :region_id
  validates_presence_of :country_of_residence
  #validates_numericality_of :age, :only_integer =>true, 
  #                        :greater_than_or_equal_to =>0, 
  #                        :message => "invalid"
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 before_filter :authenticate_user!	
	def index
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper

	def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
  
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/entertainments_helper.rb
module EntertainmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>louišP</title>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert 	%></p>
</head>
<body>
<% if user_signed_in? %>
  <div class="container">
    <div class="row">
      <div class="col-md-12 main_layout">
        <div class="col-md-3 side_bar">
          <div id="user_nav">
            <div class="image_holder">
              <% if user_signed_in? %>

                <% if @funny_image.nil? %>
                <img src="/assets/user.png">
                <% else %>
                <%= image_tag @funny_image.image_url(:thumb).to_s%>
                <% end %>  
                <% if @painting.nil? %>
                <%= image_tag "/assets/user.png", { :id=>"pro_image", :onmouseover=>"$(this).fadeTo(2000,0);", :onmouseout=>"$(this).fadeTo(2000,1);"} %>
                <% else%>
                <%= image_tag @painting.image_url(:thumb).to_s, { :id=>"pro_image", :onmouseover=>"$(this).fadeTo(2000,0);", :onmouseout=>"$(this).fadeTo(2000,1);"} %>
                <% end %>
                <% else %>
                  <img src="/assets/user.png">  
                <% end %>            
            </div>
            <% if user_signed_in? %>
              <div class = "user_name">
              <%= current_user.email %>
              <%= link_to "Sign out", destroy_user_session_path,  :method => :delete,:class => 'btn btn-xs btn-danger sign_out'%>
              </div>
              <%=  %>
              <%= link_to "UPLOAD NEW IMAGE <br>".html_safe, new_painting_path, { :class=>"btn btn_side bar_btn_height #{"#{params[:controller]}#{params[:action]}" == "paintingsnew"? "active2": ""}"}%>
              <%= link_to "UPDATE PROFILE", edit_user_registration_path, { :class=>"btn btn_side bar_btn_height #{"#{params[:controller]}#{params[:action]}" == "registrationsedit"? "active2": ""}"} %>
              <%= link_to "ADD/EDIT ENTERTAINMENT <br> ESTABLISHMENTS".html_safe, initial_page_entertainments_path, { :class=>"btn btn_side #{"#{params[:controller]}#{params[:action]}" == "entertainmentsinitial_page"? "active2": ""}"} %>
              <%= link_to "CONTACTS LIST", new_user_registration_path, { :class=>"btn btn_side bar_btn_height"} %>
              <%= link_to "CALENDAR", "javascript:void(0);", { :class=>"btn btn_side bar_btn_height"} %>
            <% else %>
              <%= link_to "sign in", new_user_session_path,{ :class=>"btn btn_side bar_btn_height"} %>
              <%= link_to "Sign up", new_user_registration_path, { :class=>"btn btn_side bar_btn_height"} %>
            <% end %>
            </div>
        </div>
        <div class="col-md-9 border-left">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <iframe src='http://louisp.info' id="info" class="iframe" name='info' width="100%" height="613px" seamless align="left"></iframe>
  <%= yield %>
<% end %>

</body>
</html>

<script type="text/javascript">
  
  
</script>